### ISSUE TITLE
Add "export" syntax as short-hand for CommonJS exports

### ISSUE THREAD

**Issue by pluma** [thlorenz/es6ify#11]
TypeScript implements ES6 module syntax along with the "export" keyword. In CommonJS-mode this creates the following behaviour:

input:

``` javascript
export class Foo {
  ...
}
export function blah() {
  ...
}
export var baz = 'quux';
// some code using Foo and baz
```

output:

``` javascript
var Foo = ... // same as before
exports.Foo = Foo;
function blah() {
  ...
}
exports.blah = blah;
var baz = 'quux';
exports.baz = baz;
// some code using Foo and baz
```

The primary gain from this is that it reduces redundancy and potential naming errors for exports.

**Comment by pluma** [comment]
Going by the [harmony spec](http://wiki.ecmascript.org/doku.php?id=harmony:modules) this seems like the right thing to do if we pretend CommonJS modules are harmony modules and `require` is harmony's `import` syntax.

Re-exporting another module would be pretty straightforward:

``` javascript
export var foo = require('foo');
```

as es6ify equivalent of harmony

``` javascript
export module foo from "foo";
```

Using decomposition this would probably be:

``` javascript
export var {bar, qux} = require('foo');
```

as es6ify equivalent of harmony

``` javascript
export import {bar, qux} from "foo";
```

**Comment by pluma** [comment]
Going by the source code I guess the es6 code itself is actually handled by traceur, not es6ify.

I wonder whether this issue can be solved at all.

**Comment by thlorenz** [comment]
`import` syntax will not work with browserify therefore it doesn't make sense to support it.

However there is some rather annoying way to make `imports` work and you are welcome to [use this](https://github.com/thlorenz/es6ify#modules).

> Going by the source code I guess the es6 code itself is actually handled by traceur, not es6ify

exactly and therefore in most cases there is nothing I can do about missing features here, `exports` not working as you expect is one of them.

Also please realize that `es6ify` is just a drop in to give you some es6 features until it becomes standard in most browsers. It was never intended to be complete.

**Comment by pluma** [comment]
I've written a small transform that can handle the more trivial exports by rewriting them to CommonJS syntax. It's a very naïve implementation that uses simple regexp matching and doesn't handle decomposition, etc, but it works for my use case.

Because it works independently of es6ify, I've open sourced it as [sixportify](https://github.com/pluma/sixportify) and published it to npm.

This solves the original feature request for me.

**Comment by thlorenz** [comment]
Nice! Will it work with es6ify, i.e. could you run the code through sixportify first and then through es6ify?

**Comment by pluma** [comment]
That's the idea. I've updated the usage example with another one that uses es6ify.

It combs through the input file, looks for lines that look like they're exporting something, removes the export keyword from the statement and then adds CommonJS exports to the end of the file for every match it found.

There are obvious problems with this (e.g. if you have a linebreak somewhere in your export declaration between the word "export" and the variable name, it won't recognize it; likewise it will match lines in multiline-comments that don't use any characters for indentation), but it does the job for me and is relatively fast.

If you wanted to do it "the right way", you would probably have to parse the input file into an ES6 AST, but that would likely be overkill (at that point you'd probably be better off extending traceur).
