### ISSUE TITLE
Don't es6ify *.json

### ISSUE THREAD

**Issue by dominykas** [thlorenz/es6ify#14]
When a valid JSON file is passed into es6ify, an error is thrown. index.js#L56 should probably have `/.js$/` as a smarter default.

Or maybe the error needs to be fixed...

(sorry, too much under pressure right now to pull request/provide more details)

**Comment by thlorenz** [comment]
Good point, I'll fix this ASAP.

**Comment by thlorenz** [comment]
Fixed in `0.4.6`
