### ISSUE TITLE
template strings don't seem to be working

### ISSUE THREAD

**Issue by malkomalko** [thlorenz/es6ify#18]
console.log(`Your userId is #{res[0].userId}`)

just logs "Your userId is #{res[0].userId}"

**Comment by malkomalko** [comment]
markdown is stripping the ` delimiters but they are there inside the console.log

**Comment by thlorenz** [comment]
That is intended see [supported features](https://github.com/thlorenz/es6ify#supported-es6-features).

Only template literals are supported - I assume that's something different? As you can see es6ify instructs traceur [to support them](https://github.com/thlorenz/es6ify/blob/fc2486502b92600ec7a0e81a1dbee932d7b84aaf/compile.js#L22).

If you can figure out a way to enhance it to support what you need, I'm happy to merge a PR :)

**Comment by malkomalko** [comment]
@thlorenz ahh, found this https://github.com/google/traceur-compiler/blob/master/test/feature/TemplateLiterals/StringRaw.js

Looks like I'm just an idiot.  It's ${} instead of #{}

**Comment by thlorenz** [comment]
@malkomalko ah great, could you add some template example then [here](https://github.com/thlorenz/es6ify/tree/master/example/src/features) please.

We could then link this from the readme, so others can learn how templates work and avoid the problems you ran into.

Thanks.
