### ISSUE TITLE
Thoughts on configuration

### ISSUE THREAD

**Issue by nhunzaker** [thlorenz/es6ify#26]
I'm building a simple Backbone app, and hit a strange bug where if I required a node module it always returned an empty object.

The configuration option you've suggested:

``` javascript
.transform(es6ify.configure(/^(?!.*node_modules)+.+\.js$/))
```

Seems to fix this, but I wonder if there's a way to make this more explicit. This is a really strange bug to decipher.

Just a thought. I love this transform!

**Comment by thlorenz** [comment]
That is an odd bug and we should probably look into what's causing this, so it'd be great if you could push up an isolated repro case to github.
Ideally I'd see the problem by just cloning the repo and then running `npm install && npm start`.

WRT the API we are [working on improving it](https://github.com/thlorenz/es6ify/pull/25) for the next version. Have a look at [this branch](https://github.com/thlorenz/es6ify/tree/v2-api) and feel free to comment in the ongoing discussion.

Thanks.

**Comment by nhunzaker** [comment]
Well... 8 months have flown by and I can no longer reproduce this. I'm going to close this out.
