### ISSUE TITLE
Correctly config filePattern in package.json?

### ISSUE THREAD

**Issue by riobard** [thlorenz/es6ify#27]
I'm trying to configure `filePattern` options in `package.json` so running browserify from command line works, but I'm stuck here

``` json
{
  ...
  "browserify": {
    "transform": [
      ["es6ify", {"config": "???"} ],
    ]
  }
  ...
}
```

What should I put there? JSON doesn't take Regular Expression literals.

**Comment by thlorenz** [comment]
Transform config is currently not supported :(
Please use es6ify as described in the Readme.

However I'd love a PR that adds this feature. Be aware though that a general API change is [pending](https://github.com/thlorenz/es6ify/pull/25)

**Comment by guzart** [comment]
@riobard Do you know of any other library that implements this type of configuration I would like to learn how they did it? Thanks.

**Comment by thlorenz** [comment]
@guzart actually it's quite simple, you just get passed an extra arg `opts` to the `transform` function as you can see from [this type signature](https://github.com/substack/node-browserify#btransformopts-tr).

This is only true for the latest browserify versions (I believe `>=v3` but am not entirely sure).

**Comment by tmcw** [comment]
@thlorenz should this be open if it's still a TODO?

**Comment by thlorenz** [comment]
@tmcw no, it's not an issue and I'm not sure it's important to have ATM.
So I closed it although I'm open to a PR that adds this feature.

**Comment by hcentelles** [comment]
Since transform config isn't supported anyone know how to configure (filePattern) es6ify while using it on karma test runner?
