### ISSUE TITLE
Unable to catch errors

### ISSUE THREAD

**Issue by ruudud** [thlorenz/es6ify#30]
Using the provided example, I am unable to get the callback on the "error" event to run when I try to transform code with errors in it.

```
var myDebug = function(err) {
  console.log('hello from myDebug');
};

es6ify.traceurOverrides = { blockBinding: true };

browserify()
  .add(es6ify.runtime)
  .transform(es6ify)
  .require(require.resolve('./src/main.js'), { entry: true })
  .bundle({ debug: true })
  .on('error', myDebug)
  .pipe(fs.createWriteStream(bundlePath));
```

In `main.js`:

```
var brokenRegex = /missing trailing slash;
```

I see that the 'error' event is in fact emitted in the code: https://github.com/thlorenz/es6ify/blob/master/index.js#L87

However, when I comment out the `transform(es6ify)` line, the error callback runs.

Any tips?

**Comment by thlorenz** [comment]
You need to add an error handler for each created stream, i.e. right below `transform` as well.

If that doesn't work you should file an issue with browserify.

FWIW es6ify [does properly emit errors](https://github.com/thlorenz/es6ify/blob/master/index.js#L87).

**Comment by ruudud** [comment]
Yeah, tried doing that as well without results. Thanks anyway.

Created https://github.com/substack/node-browserify/issues/763.

**Comment by ruudud** [comment]
Confirmed working using Browserify 4.1.3.

**Comment by thlorenz** [comment]
Great.
