### ISSUE TITLE
es6ify breaks some modules

### ISSUE THREAD

**Issue by jgillich** [thlorenz/es6ify#33]
I noticed that using es6ify wraps some modules in this:

```
module.exports = function() {
  // module code ...
  return {};
}.call(typeof global !== 'undefined' ? global : this);
```

This obviously breaks the entire module and just exports `{}` all the time.

It occured with two modules so far, [microplugin](https://github.com/brianreavis/microplugin.js) and [mprogress](https://github.com/jgillich/mprogress) (my own module). Both support multiple loaders using a really common snippet:

```
if (typeof define === 'function' && define.amd) {
    define(factory);
} else if (typeof exports === 'object') {
    module.exports = factory();
} else {
    root.MicroPlugin = factory();
}
```

 Here is a diff, first revision is just browserify, second uses es6ify:
https://gist.github.com/jgillich/fe34fc0fed0f08c317de/revisions

To reproduce the above:

```
npm install microplugin es6ify
```

`test.js`:

```
var MicroPlugin = require('microplugin');
MicroPlugin.mixin(function () {});
```

Build:

```
browserify test.js > bundle.js
browserify -t es6ify test.js > bundle2.js
```

With the latter, MicroPlugin ends up as just `{}`.

**Comment by thlorenz** [comment]
The wrapper is added by traceur (which is underlying transpiler used by es6ify).

However this wrapper 

``` js
if (typeof define === 'function' && define.amd) {
    define(factory);
} else if (typeof exports === 'object') {
    module.exports = factory();
} else {
    root.MicroPlugin = factory();
}
```

is the actual problem since it prefers AMD over module.exports, i.e. if `define` is somehow in the namespace it'll not even try module.exports which breaks browserify.

Can you confirm if this only happens when using es6ify?

As a workaround you could use [`es6ify.configure`](https://github.com/thlorenz/es6ify/blob/master/index.js#L119) and pass in a Regex for the file pattern that excludes that particular file.
That way es6ify won't touch it and therefore it'll stay intact.

**Comment by jgillich** [comment]
Yes, I double-checked it only occurs with es6ify. But it would be great if you could try it just to make sure it's not an environment issue.

**Comment by thlorenz** [comment]
Sorry too busy for that right now, could you try this on a different machine?

**Comment by jgillich** [comment]
Sorry for the delay, I have now tried it on a Ubuntu box and to my surprise I wasn't able to reproduce the issue. Tried all versions down to 1.0.3, I doubt I use an older version on the other machine (which runs Windows 7). I'll make sure I have the latest versions of es6ify, browserify and Node tomorrow and see if that fixes it.

**Comment by fizker** [comment]
I have seen the exact same thing; It fails on Windows 8, but works fine on OS X. Node and all modules are the same versions on the two machines.

**Comment by digitalsadhu** [comment]
I have the same thing, 
moment was returning {} as well as some other libs.
I tracked it down to the traceur runtime.

My fix was to remove:

```
bundle.add(es6ify.runtime)
```

and just include the runtime in the html file above the bundle.

**Comment by positlabs** [comment]
+1 

Any progress on this? It's still happening in some instances (fails on pixi.js). Adding the libs dir to the es6ify.configure method fixes the issue, but it's not ideal.

**Comment by blixt** [comment]
I just experienced this too with the "moment" package (v2.8.4).

Here's the versions this occurred with:

```
$ npm ls --depth 0
starbounded@0.1.0 /Users/blixt/src/starbounded
├── browserify@7.0.3
├── es6ify@1.6.0
├── gulp@3.8.10
├── gulp-rename@1.2.0
├── gulp-uglify@1.0.2
├── gulp-util@3.0.1
├── merge@1.2.0
├── moment@2.8.4
├── once@1.3.1
├── starbound-assets@0.8.2 -> /Users/blixt/src/js-starbound-assets
├─┬ starbound-world@0.6.1 -> /Users/blixt/src/js-starbound-world
│ └── starbound-assets@~0.8.0
├── useragent-wtf@1.0.2
└── vinyl-transform@1.0.0
```

**Comment by domenic** [comment]
So in general you should not be transpiling modules you do not own. I always configure my es6ify to ignore node_modules.

**Comment by blixt** [comment]
@domenic I was just trying to figure out a clean way to do this, the trouble being that two of the `node_modules` are owned by me and should actually be transpiled... I could of course have them transpile locally but that just makes development across all modules a hassle.

Still, I think the solution I'm currently trying to go for is to create some monstrosity of a regex to only include my modules and nothing else. :)

In the future, maybe there could be an option to exclude everything by default, unless it either contains an ES6 feature, or maybe simpler, if it's got a special marker (such as `/* es6ify transpile: true */`)?

**Comment by domenic** [comment]
So, actually, I have plans to make that work. Currently my [Traceur Runner](https://github.com/domenic/traceur-runner) project uses the package.json key `"traceur-runner": true` to only transpile packages that whitelist themselves. I am [thinking of](https://github.com/domenic/html-as-custom-elements/blob/1ce820ba493ff4a471a1e0ae40837e7c1948a426/gulpfile.js#L59-L61) reappropriating that for es6ify as well.
