### ISSUE TITLE
$traceurRuntime is not defined

### ISSUE THREAD

**Issue by sebastiandeutsch** [thlorenz/es6ify#34]
Hi,

I want to try es6ify. I have created a watchify task:

```
gulp.task('watchify', function() {
  console.log('watchify');
  var output = 'application.js'
  var bundler = watchify(BASES.src + "/javascripts/application.js", { entry: true })
  bundler.add(es6ify.runtime);
  bundler.transform(es6ify)

  var rebundle = function() {
    console.log("rebundle");
    var stream = bundler.bundle()
    return stream.on('error', $.notify.onError({ onError: true }))
      .pipe(source(output))
      .pipe(gulp.dest(BASES.build + "/javascripts/"))
  }

  bundler.on('update', rebundle);
  return rebundle()
});
```

unfortunately I get a "Uncaught ReferenceError: $traceurRuntime is not defined" in the browser. When I take a look at the generated application.js I can see the runtime, but somehow it's not required in the correct order.

**Comment by thlorenz** [comment]
Odd, never seen that, could you please provide a simpler repro (without any gulp or similar) and put this up on github?

That way we can troubleshoot this.

**Comment by sebastiandeutsch** [comment]
Sure - I've extracted the problem into this repository:

https://github.com/sebastiandeutsch/es6ify-test

Maybe I'm using watchify the wrong way (it's also a bit new to me) since this is the only difference to the browserify example. Thanks in advance for your time.

**Comment by sebastiandeutsch** [comment]
I just added the output in a separate branch:

https://github.com/sebastiandeutsch/es6ify-test/commit/6ee42763973efb5fd5ee442763226dee3f0573cb

as you can see browserify and watchify are handling the requires in different order.

**Comment by thlorenz** [comment]
Actually I'd think this would be a problem with browserify/watchify itself since es6ify cannot control how the runtime gets added to the bundle.

Could you file a bug with watchify instead and link your repro and/or this issue there?

Thanks.

**Comment by timmak** [comment]
The problem here seems to be that you need to specify the runtime as the first entry file so it can get added to the global scope and have your code as the second entry path. Might want use the new browserify watchify api to do this as well.

``` js
gulp.task('watchify', function() {
  console.log('watchify');
  var output = 'application.js'
  var bundler = watchify(es6ify.runtime, { entry: true })
  bundler.add(BASES.src + "/javascripts/application.js",);
  bundler.transform(es6ify)

  var rebundle = function() {
    console.log("rebundle");
    var stream = bundler.bundle()
    return stream.on('error', $.notify.onError({ onError: true }))
      .pipe(source(output))
      .pipe(gulp.dest(BASES.build + "/javascripts/"))
  }

  bundler.on('update', rebundle);
  return rebundle()
});
```

**Comment by ztmr** [comment]
We have the same problem, no matter if we build with watchify or browserify, we get the mentioned error everytime we use some of the ES6 extensions.

In all the cases, we call watchify/browserify as npm script, having "transform" section in the package.json.

I tried to hack it by doing:

``` JavaScript
global.$traceurRuntime = require ('es6ify').runtime;
```

...in the main entry point of the whole application, but it ended up with yet another error which we were not able to debug anyhow (undefined somewhere in the es6ify core).

So what is the expected/suggested usage of es6ify with browserify/watchify?

**Comment by torgeir** [comment]
@timmak +1 on that!

Moving from 

```
  var bundler = browserify(browserifyEntryPoint, {
    debug: !minify, // source maps
    cache: {},
    packageCache: {},
    fullPaths: watch
  });

  if (watch) {
    bundler = watchify(bundler);
  }

  bundler
    .add(es6ify.runtime)
    ...
```

to 

```
  var bundler = browserify(es6ify.runtime, {
    debug: !minify, // source maps
    cache: {},
    packageCache: {},
    fullPaths: watch
  });

  if (watch) {
    bundler = watchify(bundler);
  }

  bundler
    .add(browserifyEntryPoint)
    ...
```

Solved this issue for me.

**Comment by timmak** [comment]
@sebastiandeutsch  can we close this

**Comment by torgeir** [comment]
The examples are probably a source of confusion as browserifys .bundle() no longer accepts arguments, suggesting you move setup to the initial `browserify()`

https://github.com/thlorenz/es6ify/blob/master/example/build.js#L14

**Comment by d4goxn** [comment]
```
$ browserify -t es6ify node_modules/es6ify/node_modules/traceur/bin/traceur-runtime.js src/index.js -o dist/index.js
```

This works. But is this how I am supposed to include the Traceur runtime from the CLI, or is there a cleaner way that does not involve reaching into node_modules?

Installing traceur as a dev-dependency and passing in `node_modules/traceur/bin/traceur-runtime.js` does not work, but that is not directly relevant to this issue (presumably a version mismatch).
