### ISSUE TITLE
String.prototype.contains

### ISSUE THREAD

**Issue by jgillich** [thlorenz/es6ify#37]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/contains

Traceur seems to implement it: https://github.com/google/traceur-compiler/blob/9fddf9687bb4ddb7db21f05633d1ebbd6f815165/src/runtime/polyfills/String.js#L69

Any way to use it with this transform? It doesn't work currently, I've tried. :)

**Comment by thlorenz** [comment]
Can you try again with the newer version (we bumped traceur version used).

**Comment by jgillich** [comment]
No difference with 1.3.

**Comment by thlorenz** [comment]
Have you tried that this actually works with traceur itself? You can try [here](http://google.github.io/traceur-compiler/demo/repl.html).

If it's not working there then es6ify can do nothing about it and you should file a bug with [traceur](https://github.com/google/traceur-compiler).

**Comment by jgillich** [comment]
Ok, the issue is that traceur has a runtime component that is not included in es6ify. There is a issue about that here: https://github.com/google/traceur-compiler/issues/1007

Any plans to include it? I'm however not sure if it is a good idea because its quite a bit of code and the great thing about this transform is that it doesn't add much.

**Comment by guzart** [comment]
You can include it using the `browserify#add` method, or there's a [bower component](https://github.com/jmcriffey/bower-traceur-runtime), and [npm standalone package](https://www.npmjs.org/package/traceur-runtime)

```
browserify()
  .add(es6ify.runtime)
  .transform(es6ify)
  ...
```

**Comment by jgillich** [comment]
Ah that's neat, thanks!

**Comment by thlorenz** [comment]
Ah wow, I had assumed you read the [readme](https://github.com/thlorenz/es6ify#es6ify-) and already knew that ;)

If that example is not obvious I'm open for improvements.

**Comment by jgillich** [comment]
I usually read the readme, but it doesn't mention what the runtime is needed for in detail. :wink:
I'll send you a PR.
