### ISSUE TITLE
maybe we need peerDependencies traceur

### ISSUE THREAD

**Issue by cncolder** [thlorenz/es6ify#43]
write a special traceur version in dependencies is not a good idea.
this stop user update to latest version.
if i play with traceur both on server side and browser side. i wish use the same traceur version to unsure my es6 code compile to the same result.

**Comment by thlorenz** [comment]
Well, es6ify directly requires (and is tested against) specific versions of traceur, so it needs to be a dependency.
However I try to keep the traceur version up to date.

Just use the latest traceur and you should be fine. If currently es6ify is not using the latest traceur please submit a PR.
