### ISSUE TITLE
Peer-depend on Traceur

### ISSUE THREAD

**Issue by domenic** [thlorenz/es6ify#45]
We had a long discussion over in https://github.com/karma-runner/karma/issues/1166 about how Traceur-using build tools should depend on Traceur. Our conclusion was that the best way to deal with this was for all of them to peer-depend on Traceur, instead of depend. That way, you get a single Traceur version for the whole project, instead of es6ify bundling one version, and karma-traceur-preprocessor bundling another, and so on. It also allows the user to control the version of Traceur they use, instead of having it controlled by their tools; this allows them to e.g. upgrade without having to pull-request es6ify and then upgrade their es6ify dependency.

Traceur is kind of a special-case, being pre-1.0 but needing collaboration between different tools. What we settled on was to peer-depend on e.g. ">= 0.0.60" if the tool depends on features only introduced in 0.0.60. (For example karma-traceur-preprocessor depends on features introduced in 0.0.51, but after we fix https://github.com/karma-runner/karma-traceur-preprocessor/issues/8 it will depend on features introduced in 0.0.60.) Normally you would want to put an upper limit, but Traceur does not have a stable API yet, so you can't do that effectively.

What do you think? Ready to move to a peer dependency? I'm filing similar issues on grunt-traceur and gulp-traceur.

**Comment by thlorenz** [comment]
I'm not sure how that would work. es6ify calls methods on traceur directly, so it needs to be installed as a dependency.
Otherwise we'd get into similar situations that the backbone/jquery debacle did.

The better option IMO would be to make the version range less specific, so that npm dedupe could select a version that makes both tools happy.

**Comment by domenic** [comment]
npm dedupe is one way out of this, I suppose. But it's fine to call methods on a peer dependency. I don't understand the reference to backbone/jquery debacle.

**Comment by thlorenz** [comment]
backbone had a `require('jquery')` but didn't list it as a dependency.

So if someone installs es6ify it should work out of the box. If it doesn't declare traceur as a dependency the user would have to know to install it. I really don't like that idea.

**Comment by domenic** [comment]
If it declares Traceur as a peer dependency it will be installed alongside es6ify.

**Comment by thlorenz** [comment]
So is the main difference basically that it'd be kind of like installing traceur but deduping in one step?

So in this case should I understand peerDep to mean "install traceur version that works with all installed packages as a sibling instead as a child"?

**Comment by domenic** [comment]
> So is the main difference basically that it'd be kind of like installing traceur but deduping in one step?

Yeah, exactly.

> So in this case should I understand peerDep to mean "install traceur version that works with all installed packagesnode_modules as a sibling instead as a child"?

I think so. It would also prevent you from installing incompatible Traceurs. So let's say you have been working with Traceur 0.0.58 in your project. Since it is pre-1.0.0, you are pinning it exactly in your package.json. You then install es6ify@1.2.3, which peer-depends on Traceur >= 0.0.50. All is good.

Later, Traceur updates its compile API slightly in 0.0.59, and es6ify breaks. (This is because we are treating Traceur specially: it is a pre-1.0.0 package with a large ecosystem, so we err on the side of potential errors instead of over-strictness by using >= instead of ^.) es6ify fixes itself, and releases es6ify@1.2.4, which peer-depends on Traceur >= 0.0.59. Now, if your project updates its es6ify dep without upgrading its Traceur dep, you get an error. Which is good!

**Comment by thlorenz** [comment]
> so we err on the side of potential errors instead of over-strictness by using >= instead of ^.) 

In the past pretty much with every traceur upgrade some things (mostly tests) needed to be adjusted.
So even with peerDeps I'd like to keep upgrades controlled, i.e. at this point I'd set it to something like:
`> 0.0. 30 <= 0.0.55`. ( lots of API changes introduced after `0.0.10` ish). 

Otherwise we end up with people using es6ify with all kinds of (possible incompatible) newer versions and run into obscure bugs which will be very time consuming to figure out.

**Comment by domenic** [comment]
I guess it is a question of how much you want to protect users vs. let them potentially get in trouble.

Ideally, users should be including Traceur as their own dependency, and pinning it to a known-working-with-their-stuff version. The downside is that for people who don't do this, there is the danger of changes in Traceur flowing through the newly-permissive es6ify constraint and breaking peoples' apps. But this is also easy to fix: they just need to add `"traceur": "exact version before the breaking change in Traceur was introduced"` to their package.json.

**Comment by thlorenz** [comment]
Well I'd be fine with that except for one minor detail.

> people who don't do this

Those people will come here and file tons of issues, I'd like to come up with a strategy that avoids that.
I rather handle PRs that upgrade traceur version and run the tests every time I do so to ensure everything still works and if not fix it.

**Comment by domenic** [comment]
Aww :(.

I guess in that case the only potential benefit of peer dependencies would be the pre-deduping, within the narrow version range you do support. Not sure it's as worth it. Although even without peer dependencies it would be good to widen the version range downward (i.e. currently you are 0.0.55, maybe you should be >= 0.0.51 <= 0.0.55) so that dedupe can work more effectively.

**Comment by domenic** [comment]
Actually now that I think about it the peer dependencies decision depends on your opinion of what should happen in this situation:
- Someone uses es6ify + some other Traceur-using tool. (Say, mocha-traceur.)
- es6ify is built and tested with 0.0.55, and mocha-traceur is built and tested with 0.0.59.

Should you get an error trying to use them together? (Conflicting peer dependencies will generate such an error.) Or should you get your es6ify-produced code running differently than your tests? (As would happen with straight-up dependencies, in this non-dedupable case.) I am not sure which is worse :(

**Comment by thlorenz** [comment]
You seem to be more aware of what's needed here and how to handle that in the future (I'm not even using es6ify in my own projects).
So I added you as collaborator and npm package owner.

Feel free to make the necessary changes, publish new versions, etc. (and handle user issues ;) )

Also please add yourself to the contributors list in the `package.json` during the next update.

Thanks.

**Comment by domenic** [comment]
Oh, OK! :) Now I have so much responsibility... hmm.

**Comment by thlorenz** [comment]
That was the idea :)
You make the decision and handle the consequences (issues I predict).

If no issues come, even better.

Win Win situation for all of us.

**Comment by ruimarinho** [comment]
@domenic, there seems to be very different opinions regarding `peerDeps`. For instance, sindresorhus is against this change on [gulp-regenerator](https://github.com/sindresorhus/gulp-regenerator/issues/1). Are you planning on releasing a new version of `es6ify` with `traceur@0.0.60` as a direct or peer dep?

**Comment by domenic** [comment]
The plan is to wait for traceur to release a 1.0 (probably within the next couple days), then do another 1.x release of es6ify that (non-peer-)depends on Traceur, then do a 2.0 release of es6ify that peer-depends.
