### ISSUE TITLE
Update to the latest traceur

### ISSUE THREAD

**Issue by mourner** [thlorenz/es6ify#48]
The latest version of Traceur now sports an awesome block binding implementation that avoids using try/catch and is pretty fast, along with other fixes/improvements. So it would be great to see this in es6ify finally.

**Comment by domenic** [comment]
Yes, unfortunately it also changed the compiler API pretty drastically, and most of the tests are failing. See #46.

**Comment by mourner** [comment]
Ah, sorry, didn't see the PR.
