### ISSUE TITLE
arrowFunction method vs `this`

### ISSUE THREAD

**Issue by ztmr** [thlorenz/es6ify#51]
The following code does not work properly:

```
module.exports = {
    name: 'World',
    hello: () => {
      console.log ('Hello ' + this.name + '!');
    }
};
```

because `this` becomes `$__0` and `$__0` is set to `this` in the scope of the CommonJS closure instead of the scope of the first parent object (module.exports) as expected:

```
[...CommonJS closure start...]
var $__0 = this;
module.exports = {
    name: 'World',
    hello: function () {
      console.log ('Hello ' + $__0.name + '!');
    }
};
[...CommonJS closure end...]
```

The result is that arrow functions can be used only for object methods not referencing `this`.
I have not tested it with prototypes yet, but I expect the scenario to be the same.
The class-way works nicely:

```
class HelloClass {
    constructor () { this.name = 'World'; }
    hello () { console.log ('Hello ' + this.name + '!'); }
}
module.exports = new HelloClass ();
```

**Comment by domenic** [comment]
This is how ES6 works. => uses lexical this, and should not be used for methods. I advise using method shorthand, e.g.

``` js
module.exports = {
    name: 'World',
    hello() {
      console.log ('Hello ' + this.name + '!');
    }
};
```
