### ISSUE TITLE
Upgrade to latest version of browserify

### ISSUE THREAD

**Issue by iwillig** [thlorenz/es6ify#55]
As a user of es6ify I would like to be able to use the latest version of browserify. 

It appears that there were api changes between 3.x.x (what we are using) and 5.x.x (current). We will need to address these changes. 
- [ ] Update to use latest api
- [ ] Write test to check this
- [ ] Test in sample project

**Comment by thlorenz** [comment]
@iwillig when you say _we_ does that mean you'll provide a PR for these things?
_We_'d greatly appreciate it :)

**Comment by iwillig** [comment]
Yeah.. going to give it a go..

**Comment by iwillig** [comment]
Work happening here, 

https://github.com/thlorenz/es6ify/pull/56

This seems to work, but I should do some deep digging tomorrow.
