### ISSUE TITLE
ES6 comprehensions no longer in TC39 draft

### ISSUE THREAD

**Issue by qmmr** [thlorenz/es6ify#57]
Seems like we're not going to have comprehensions in ES6 according to [this meeting](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-07/jul-30.md#47-revisit-comprehension-decision-from-last-meeting). Should they be removed from the es6ify?

**Comment by domenic** [comment]
This will get fixed when we upgrade Traceur.

**Comment by domenic** [comment]
1.5.0 has a new Traceur with new default options.
