### ISSUE TITLE
Using es6ify on a command line run of browserify?

### ISSUE THREAD

**Issue by cymen** [thlorenz/es6ify#60]
Is it possible to configure the es6ify options on the command line when running browserify that way? I ask because I'd like to try using es6ify with browserify-rails but it runs browserify via the command line. I've been successful with getting proxyquireify running like that but not sure how to do things like pass ignoring the node_modules directory to es6ify.

**Comment by domenic** [comment]
This is more of a general browserify transform question. I vaguely remember some package.json syntax? Unsure though.

**Comment by cymen** [comment]
@domenic Thanks -- that prompting made me find the solution (I think!). The issue is related here if anyone else hits the same thing and is curious.
