### ISSUE TITLE
Not working with grunt-browserify

### ISSUE THREAD

**Issue by NickTsitlakidis** [thlorenz/es6ify#61]
Hey there.
I'm having a weird issue.
I use grunt-browserify as a task and all my transforms are declared in my gruntfile.
Any thoughts on how to add es6ify there as well?

I have tried adding it as a transform but Browserify fails and throws a message that a reserved word was found (I'm trying to use classes).

I guess that the problem is with the rest of the configuration (add,require etc). Any guidelines would be greatly appreciated.
Thanks.

**Comment by thlorenz** [comment]
Sorry no idea, I don't use grunt.
es6ify is pretty much like any transform, so I'd suggest asking this question on the grunt-browserify page.

In the meantime just config things in the `package.json` like browserify intends you to do ;)
