### ISSUE TITLE
Turning off sourcemaps fails

### ISSUE THREAD

**Issue by torarnek** [thlorenz/es6ify#64]
Per default I get the following for every required module
//# sourceMappingURL=< compileOutput>

When I try to turn off source maps
es6ify.traceurOverrides = { sourceMaps: false };

I get:
TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]
[TypeError: Cannot use 'in' operator to search for 'version' in null]

Is there a way to turn of source maps?

I am currently running through gulp.
browserify: 4.2.3

**Comment by domenic** [comment]
Can you give us test case code, that does not run through gulp?

**Comment by torarnek** [comment]
Well, in your example, after running node build.js, in example/public/js/bundle.js on line 7:
//# sourceMappingURL=< compileOutput>

When adding the following to build.js:
es6ify.traceurOverrides = { sourceMaps: false };
and run node build.js:

Please open the index.html inside example/public.
{ [TypeError: Cannot use 'in' operator to search for 'version' in null while parsing file: /Users/torkvalo/dev/es6ify/example/src/main.js]
  filename: '/Users/torkvalo/dev/es6ify/example/src/main.js',
  stream:
   { _readableState:
