### ISSUE TITLE
Update traceur

### ISSUE THREAD

**Issue by megawac** [thlorenz/es6ify#66]
`Traceur@0.0.74` please :) I want some generic types and super updates

**Comment by domenic** [comment]
Ugh, annoyed that Traceur is getting so many non-ES6 features, which makes this package's name more and more of a lie.

PR welcome to update. Although one day I'll just do #45 and then it'll work with any versions.

**Comment by domenic** [comment]
Updated to Traceur 0.0.79 in es6ify 1.6.0. Enjoy your AtScript; the rest of us will continue using ES6...
