### ISSUE TITLE
import syntax?

### ISSUE THREAD

**Issue by trusktr** [thlorenz/es6ify#71]
Does this support import syntax? f.e.

``` js
import something from "something.js";
```

**Comment by thlorenz** [comment]
Give it a try?

**Comment by trusktr** [comment]
Ah, I see that part in the README. Looks awesome. What about multiple named exports along with a default export in a single module?

**Comment by thlorenz** [comment]
I honestly don't know, just experiment ;)

**Comment by domenic** [comment]
As you may have gathered, es6ify wraps Traceur, and so asking how Traceur works is best not done in the bug tracker for es6ify. I'd suggest StackOverflow, the Traceur Google Group, or if you find an actual bug, the Traceur bug tracker.
