### ISSUE TITLE
Slow traceur runtime compilation

### ISSUE THREAD

**Issue by hmaurer** [thlorenz/es6ify#82]
Hello!

I am using es6ify with reactify and the traceur runtime, but compilation is extremely slow (>4seconds). I assume browserify is parsing the traceur runtime, not I am not sure how to prevent that (couldn't figure out the right noparse option). 

Here is the build task I am using:

```
gulp.task('browserify', function(){
   var bundler = browserify(es6ify.runtime,{
      noparse: ['reflux', 'lodash'],
      transform: [reactify],
      extensions: ['.jsx'],
      debug: true,
      cache: {},
      packageCache: {},
      fullPaths: true
   });
   bundler = watchify(bundler);
   bundler.add('./resources/assets/js/main.jsx');
   bundler.transform(es6ify.configure(/.jsx/));

   var rebundle = function() {
      return bundler.bundle()
         .on('error', function(e) { gutil.log(e.message) })
         .pipe(source('bundle.js'))
         .pipe(buffer())
         .pipe(gulp.dest('public/js'));
   };

   bundler.on('update', rebundle);
   return rebundle();
});
```

**Comment by jmm** [comment]
So omitting the runtime fixes the slow compilation? You tried: `noparse: [es6ify.runtime]`? What version of browserify?

**Comment by hmaurer** [comment]
Mmmh that doesn't seem to fix it. I switched to Babel and everything works fine now though; thanks!
