### ISSUE TITLE
How to enable async/await from the command line?

### ISSUE THREAD

**Issue by niloy** [thlorenz/es6ify#83]
I used the following command

``` shell
browserify -t [ es6ify --asyncFunctions ] test.js
```

But it is still not working. The contents are test.js are

``` js
function timeout(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function asyncValue(value) {
  await timeout(50);
  return value;
}

(async function() {
  var value = await asyncValue(42).catch(console.error.bind(console));
  assert.equal(42, value);
  done();
})();
```

**Comment by thlorenz** [comment]
async await isn't ES6 (it's ES7).
I don't know where you got the `--asyncFunctions` flag from but that feature doesn't exist.

**Comment by niloy** [comment]
Its there in the README.md.

https://github.com/thlorenz/es6ify#es6ifytraceuroverrides-1

And reading the browserify doc, that is the syntax to pass arguments to transforms.

**Comment by thlorenz** [comment]
es6ify doesn't currently accept transform arguments that way, sorry.
